"""phase2_active_learning

Revision ID: 96666ad6e3f4
Revises: b16bd4264820
Create Date: 2026-02-28 17:29:06.055418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96666ad6e3f4'
down_revision: Union[str, Sequence[str], None] = 'b16bd4264820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('topic_slug', sa.String(length=100), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('question_it', sa.Text(), nullable=False),
    sa.Column('choices_json', sa.Text(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation_json', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_questions_subject'), 'exam_questions', ['subject'], unique=False)
    op.create_index(op.f('ix_exam_questions_topic_slug'), 'exam_questions', ['topic_slug'], unique=False)
    op.create_table('practice_test_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('time_expired', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_slug', sa.String(length=100), nullable=False),
    sa.Column('front_it', sa.Text(), nullable=False),
    sa.Column('back_it', sa.Text(), nullable=False),
    sa.Column('front_en', sa.Text(), nullable=True),
    sa.Column('back_en', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['topic_slug'], ['topics.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_topic_slug'), 'flashcards', ['topic_slug'], unique=False)
    op.create_table('practice_test_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('chosen_index', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['practice_test_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_test_answers_attempt_id'), 'practice_test_answers', ['attempt_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_slug', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_slug'], ['topics.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_topic_slug'), 'quiz_attempts', ['topic_slug'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_slug', sa.String(length=100), nullable=False),
    sa.Column('question_it', sa.Text(), nullable=False),
    sa.Column('choices_json', sa.Text(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation_json', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_slug'], ['topics.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_topic_slug'), 'quiz_questions', ['topic_slug'], unique=False)
    op.create_table('srs_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.Column('card_json', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_srs_states_due_at'), 'srs_states', ['due_at'], unique=False)
    op.create_index(op.f('ix_srs_states_flashcard_id'), 'srs_states', ['flashcard_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_srs_states_flashcard_id'), table_name='srs_states')
    op.drop_index(op.f('ix_srs_states_due_at'), table_name='srs_states')
    op.drop_table('srs_states')
    op.drop_index(op.f('ix_quiz_questions_topic_slug'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_quiz_attempts_topic_slug'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_practice_test_answers_attempt_id'), table_name='practice_test_answers')
    op.drop_table('practice_test_answers')
    op.drop_index(op.f('ix_flashcards_topic_slug'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_table('practice_test_attempts')
    op.drop_index(op.f('ix_exam_questions_topic_slug'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_subject'), table_name='exam_questions')
    op.drop_table('exam_questions')
    # ### end Alembic commands ###
