"""initial_schema

Revision ID: b16bd4264820
Revises: 
Create Date: 2026-02-28 15:27:32.096444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16bd4264820'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title_it', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('order_in_subject', sa.Integer(), nullable=False),
    sa.Column('content_it', sa.Text(), nullable=True),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_index(op.f('ix_topics_subject'), 'topics', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_subject'), table_name='topics')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
