"""v1_ux_improvements

Revision ID: f9d56859adcc
Revises: 96666ad6e3f4
Create Date: 2026-03-01 23:12:02.762818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9d56859adcc'
down_revision: Union[str, Sequence[str], None] = '96666ad6e3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_slug', sa.String(length=100), nullable=False),
    sa.Column('section_slug', sa.String(length=100), nullable=False),
    sa.Column('question_it', sa.Text(), nullable=False),
    sa.Column('choices_json', sa.Text(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_slug'], ['topics.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_slug', 'section_slug', name='uq_section_question')
    )
    with op.batch_alter_table('section_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_questions_topic_slug'), ['topic_slug'], unique=False)

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=50), nullable=True))
        batch_op.alter_column('topic_slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_subject'), ['subject'], unique=False)
        # FK constraint has no name in SQLite — batch_alter rebuilds the table without it

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_subject'))
        batch_op.alter_column('topic_slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('subject')

    with op.batch_alter_table('section_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_questions_topic_slug'))

    op.drop_table('section_questions')
    # ### end Alembic commands ###
